name: GitHub Actions Test Multiple Jobs
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "test=world" >> "$GITHUB_OUTPUT"

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job2.outputs.output1}}
        run: echo "$OUTPUT1 $OUTPUT2"

